#release configuration
#Sun Jun 15 19:41:32 CEST 2025
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.local.jarios\:email-helper=1.0.7-SNAPSHOT
project.rel.local.jarios\:email-helper=1.0.6
project.scm.local.jarios\:email-helper.connection=scm\:git\:https\://github.com/contratacionmalaga/email-helper.git
project.scm.local.jarios\:email-helper.developerConnection=scm\:git\:git@github.com\:contratacionmalaga/email-helper.git
project.scm.local.jarios\:email-helper.tag=HEAD
project.scm.local.jarios\:email-helper.url=https\://github.com/contratacionmalaga/email-helper
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[RELEASE]
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=v1.0.6
scm.tagNameFormat=v@{project.version}
scm.url=scm\:git\:git@github.com\:contratacionmalaga/email-helper.git
