# DATOS DE CONFIGURACIÓN DE LA APLICACIÓN

# *******************************************************************
# RUTA DONDE SE ENCUENTRAN LOS FICHEROS GC QUE SERÁN IMPORTADOS
config.name=Importación de ficheros GC

# *******************************************************************
# RUTA DONDE SE ENCUENTRAN LOS FICHEROS GC QUE SERÁN IMPORTADOS
config.path=data/gc

# *******************************************************************
# PREFIJO QUE TENDRÁN LAS TABLAS EN LA BASE DE DATOS`
config.prefijo=place_

# *******************************************************************
# ESQUEMA
config.esquema=imp_placsp_gc

# *******************************************************************
# PACKAGE NAME
config.package_name=local.jarios.entity
