# DATOS PARA ENVIAR MAIL DESDE LA APLICACIÓN
mail.smtp.host=correo.malaga.es
mail.smtp.auth=true
mail.smtp.port=587
mail.smtp.socketFactory.port=587
mail.smtp.ssl.checkserveridentity=true
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.ssl.trust=correo.malaga.es
mail.smtp.starttls.enable=true

mail.user=jarios@malaga.es
mail.password=XSNTOKKFORTGCHOV
mail.from=jarios@malaga.es
mail.to=jarios@malaga.es
