# # # # # # # # # # # # # # # # # # # # #
# Valores del logging de Hibernate
#
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.highlight_sql=false
hibernate.generata_statistics=true

# # # # # # # # # # # # # # # # # # # # #
# Valores de generación del esquema. Opciones:
#
#       validate: validate the schema, makes no changes to the database.
#       update: update the schema si detecta cambios.
#       create: creates the schema, destroying previous data.
#       create-drop: drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
#       none: does nothing with the schema, makes no changes to the database-->
hibernate.hbm2ddl.auto=create

#
hibernate.ssl=false

# # # # # # # # # # # # # # # # # # # # #
# Caché de segundo nivel
#
#hibernate.cache.use_second_level_cache=true
#hibernate.cache.region.factory_class=org.hibernate.cache.caffeine.CaffeineRegionFactory
#hibernate.cache.use_query_cache=true

# # # # # # # # # # # # # # # # # # # # #
# Configuración de la JTA Platform
#
hibernate.transaction.jta.platform=org.hibernate.service.jta.platform.internal.NarayanaJtaPlatform

# # # # # # # # # # # # # # # # # # # # #
# Configuración de la base de datos
#
hibernate.principal.url=jdbc:postgresql://localhost:5432/contratacion
hibernate.principal.driver=org.postgresql.Driver
hibernate.principal.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.principal.username=postgres
hibernate.principal.password=malaga

# # # # # # # # # # # # # # # # # # # # #
# Establecer HikariCP (cuando se usa Hibernate 6, es compatible)
#
hibernate.hikari.maximumPoolSize=10
hibernate.hikari.minimumIdle=5
hibernate.hikari.connectionTimeout=30000
hibernate.hikari.idleTimeout=600000
hibernate.hikari.maxLifetime=1800000
hibernate.hikari.poolName=JaRiosHikariCP